# docker run --name expense-manager-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker 
# -e POSTGRESQL_DATABASE=expensemanagerdb -p 5432:5432 bitnami/postgresql

version: '3.1'

services:
  expense-manager-pg:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=expensemanagerdb
    ports:
      - 5432:5432
